/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  EmployeeEnrollment as PrismaEmployeeEnrollment,
} from "@prisma/client";

export class EmployeeEnrollmentServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.EmployeeEnrollmentCountArgs, "select">
  ): Promise<number> {
    return this.prisma.employeeEnrollment.count(args);
  }

  async employeeEnrollments<T extends Prisma.EmployeeEnrollmentFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.EmployeeEnrollmentFindManyArgs>
  ): Promise<PrismaEmployeeEnrollment[]> {
    return this.prisma.employeeEnrollment.findMany<Prisma.EmployeeEnrollmentFindManyArgs>(
      args
    );
  }
  async employeeEnrollment<T extends Prisma.EmployeeEnrollmentFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.EmployeeEnrollmentFindUniqueArgs>
  ): Promise<PrismaEmployeeEnrollment | null> {
    return this.prisma.employeeEnrollment.findUnique(args);
  }
  async createEmployeeEnrollment<T extends Prisma.EmployeeEnrollmentCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.EmployeeEnrollmentCreateArgs>
  ): Promise<PrismaEmployeeEnrollment> {
    return this.prisma.employeeEnrollment.create<T>(args);
  }
  async updateEmployeeEnrollment<T extends Prisma.EmployeeEnrollmentUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.EmployeeEnrollmentUpdateArgs>
  ): Promise<PrismaEmployeeEnrollment> {
    return this.prisma.employeeEnrollment.update<T>(args);
  }
  async deleteEmployeeEnrollment<T extends Prisma.EmployeeEnrollmentDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.EmployeeEnrollmentDeleteArgs>
  ): Promise<PrismaEmployeeEnrollment> {
    return this.prisma.employeeEnrollment.delete(args);
  }
}
