/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  TeamBuildingActivity as PrismaTeamBuildingActivity,
} from "@prisma/client";

export class TeamBuildingActivityServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.TeamBuildingActivityCountArgs, "select">
  ): Promise<number> {
    return this.prisma.teamBuildingActivity.count(args);
  }

  async teamBuildingActivities<
    T extends Prisma.TeamBuildingActivityFindManyArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.TeamBuildingActivityFindManyArgs>
  ): Promise<PrismaTeamBuildingActivity[]> {
    return this.prisma.teamBuildingActivity.findMany<Prisma.TeamBuildingActivityFindManyArgs>(
      args
    );
  }
  async teamBuildingActivity<
    T extends Prisma.TeamBuildingActivityFindUniqueArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.TeamBuildingActivityFindUniqueArgs>
  ): Promise<PrismaTeamBuildingActivity | null> {
    return this.prisma.teamBuildingActivity.findUnique(args);
  }
  async createTeamBuildingActivity<
    T extends Prisma.TeamBuildingActivityCreateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.TeamBuildingActivityCreateArgs>
  ): Promise<PrismaTeamBuildingActivity> {
    return this.prisma.teamBuildingActivity.create<T>(args);
  }
  async updateTeamBuildingActivity<
    T extends Prisma.TeamBuildingActivityUpdateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.TeamBuildingActivityUpdateArgs>
  ): Promise<PrismaTeamBuildingActivity> {
    return this.prisma.teamBuildingActivity.update<T>(args);
  }
  async deleteTeamBuildingActivity<
    T extends Prisma.TeamBuildingActivityDeleteArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.TeamBuildingActivityDeleteArgs>
  ): Promise<PrismaTeamBuildingActivity> {
    return this.prisma.teamBuildingActivity.delete(args);
  }
}
