/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { TeamBuildingActivity } from "./TeamBuildingActivity";
import { TeamBuildingActivityCountArgs } from "./TeamBuildingActivityCountArgs";
import { TeamBuildingActivityFindManyArgs } from "./TeamBuildingActivityFindManyArgs";
import { TeamBuildingActivityFindUniqueArgs } from "./TeamBuildingActivityFindUniqueArgs";
import { DeleteTeamBuildingActivityArgs } from "./DeleteTeamBuildingActivityArgs";
import { TeamBuildingActivityService } from "../teamBuildingActivity.service";
@graphql.Resolver(() => TeamBuildingActivity)
export class TeamBuildingActivityResolverBase {
  constructor(protected readonly service: TeamBuildingActivityService) {}

  async _teamBuildingActivitiesMeta(
    @graphql.Args() args: TeamBuildingActivityCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [TeamBuildingActivity])
  async teamBuildingActivities(
    @graphql.Args() args: TeamBuildingActivityFindManyArgs
  ): Promise<TeamBuildingActivity[]> {
    return this.service.teamBuildingActivities(args);
  }

  @graphql.Query(() => TeamBuildingActivity, { nullable: true })
  async teamBuildingActivity(
    @graphql.Args() args: TeamBuildingActivityFindUniqueArgs
  ): Promise<TeamBuildingActivity | null> {
    const result = await this.service.teamBuildingActivity(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TeamBuildingActivity)
  async deleteTeamBuildingActivity(
    @graphql.Args() args: DeleteTeamBuildingActivityArgs
  ): Promise<TeamBuildingActivity | null> {
    try {
      return await this.service.deleteTeamBuildingActivity(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
