/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { RecognitionProgram } from "./RecognitionProgram";
import { RecognitionProgramCountArgs } from "./RecognitionProgramCountArgs";
import { RecognitionProgramFindManyArgs } from "./RecognitionProgramFindManyArgs";
import { RecognitionProgramFindUniqueArgs } from "./RecognitionProgramFindUniqueArgs";
import { DeleteRecognitionProgramArgs } from "./DeleteRecognitionProgramArgs";
import { RecognitionProgramService } from "../recognitionProgram.service";
@graphql.Resolver(() => RecognitionProgram)
export class RecognitionProgramResolverBase {
  constructor(protected readonly service: RecognitionProgramService) {}

  async _recognitionProgramsMeta(
    @graphql.Args() args: RecognitionProgramCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [RecognitionProgram])
  async recognitionPrograms(
    @graphql.Args() args: RecognitionProgramFindManyArgs
  ): Promise<RecognitionProgram[]> {
    return this.service.recognitionPrograms(args);
  }

  @graphql.Query(() => RecognitionProgram, { nullable: true })
  async recognitionProgram(
    @graphql.Args() args: RecognitionProgramFindUniqueArgs
  ): Promise<RecognitionProgram | null> {
    const result = await this.service.recognitionProgram(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => RecognitionProgram)
  async deleteRecognitionProgram(
    @graphql.Args() args: DeleteRecognitionProgramArgs
  ): Promise<RecognitionProgram | null> {
    try {
      return await this.service.deleteRecognitionProgram(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
