/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { TrainingProgram } from "./TrainingProgram";
import { TrainingProgramCountArgs } from "./TrainingProgramCountArgs";
import { TrainingProgramFindManyArgs } from "./TrainingProgramFindManyArgs";
import { TrainingProgramFindUniqueArgs } from "./TrainingProgramFindUniqueArgs";
import { DeleteTrainingProgramArgs } from "./DeleteTrainingProgramArgs";
import { TrainingProgramService } from "../trainingProgram.service";
@graphql.Resolver(() => TrainingProgram)
export class TrainingProgramResolverBase {
  constructor(protected readonly service: TrainingProgramService) {}

  async _trainingProgramsMeta(
    @graphql.Args() args: TrainingProgramCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [TrainingProgram])
  async trainingPrograms(
    @graphql.Args() args: TrainingProgramFindManyArgs
  ): Promise<TrainingProgram[]> {
    return this.service.trainingPrograms(args);
  }

  @graphql.Query(() => TrainingProgram, { nullable: true })
  async trainingProgram(
    @graphql.Args() args: TrainingProgramFindUniqueArgs
  ): Promise<TrainingProgram | null> {
    const result = await this.service.trainingProgram(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TrainingProgram)
  async deleteTrainingProgram(
    @graphql.Args() args: DeleteTrainingProgramArgs
  ): Promise<TrainingProgram | null> {
    try {
      return await this.service.deleteTrainingProgram(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
