/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PerformanceReview } from "./PerformanceReview";
import { PerformanceReviewCountArgs } from "./PerformanceReviewCountArgs";
import { PerformanceReviewFindManyArgs } from "./PerformanceReviewFindManyArgs";
import { PerformanceReviewFindUniqueArgs } from "./PerformanceReviewFindUniqueArgs";
import { DeletePerformanceReviewArgs } from "./DeletePerformanceReviewArgs";
import { PerformanceReviewService } from "../performanceReview.service";
@graphql.Resolver(() => PerformanceReview)
export class PerformanceReviewResolverBase {
  constructor(protected readonly service: PerformanceReviewService) {}

  async _performanceReviewsMeta(
    @graphql.Args() args: PerformanceReviewCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [PerformanceReview])
  async performanceReviews(
    @graphql.Args() args: PerformanceReviewFindManyArgs
  ): Promise<PerformanceReview[]> {
    return this.service.performanceReviews(args);
  }

  @graphql.Query(() => PerformanceReview, { nullable: true })
  async performanceReview(
    @graphql.Args() args: PerformanceReviewFindUniqueArgs
  ): Promise<PerformanceReview | null> {
    const result = await this.service.performanceReview(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PerformanceReview)
  async deletePerformanceReview(
    @graphql.Args() args: DeletePerformanceReviewArgs
  ): Promise<PerformanceReview | null> {
    try {
      return await this.service.deletePerformanceReview(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
